import { Threat } from "@/types";

export const MOCK_THREATS: Threat[] = [
  {
    id: "threat-101",
    cve: "CVE-2026-9912",
    vendor: "OpenSSL",
    product: "Cryptography Library",
    threatType: "Remote Code Execution (RCE)",
    severity: "Critical",
    publishedDate: "2026-07-02",
    source: "VulnDB Analyst Team",
    summary: "A heap buffer overflow vulnerability exists in the OpenSSL ASN.1 parser during verification of malformed certificates. An unauthenticated remote attacker can exploit this flaw to execute arbitrary code or trigger a denial of service (DoS) crash on internet-facing TLS gateways.",
    remediation: "Apply the latest vendor patch immediately by upgrading OpenSSL to version 3.4.1 or higher.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2026-9912",
      "https://www.openssl.org/news/secadv/20260702.txt"
    ],
    cvssScore: 9.8,
    attackVector: "Network (AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H)",
    status: "active",
    countryCode: "US",
    timestamp: "2026-07-17T09:40:00Z"
  },
  {
    id: "threat-102",
    cve: "CVE-2026-1025",
    vendor: "Microsoft",
    product: "Windows Kernel",
    threatType: "Privilege Escalation",
    severity: "High",
    publishedDate: "2026-06-18",
    source: "MSRC Portal",
    summary: "An input validation flaw in the Windows Kernel Input-Output Manager (I/O manager) allows local users to execute processes with SYSTEM permissions.",
    remediation: "Deploy Microsoft Security Bulletin KB5029190 across all affected active directories.",
    references: [
      "https://msrc.microsoft.com/update-guide/vulnerability/CVE-2026-1025"
    ],
    cvssScore: 8.8,
    attackVector: "Local (AV:L/AC:H/PR:L/UI:N/S:C/C:H/I:H/A:H)",
    status: "active",
    countryCode: "CN",
    timestamp: "2026-07-17T08:15:00Z"
  },
  {
    id: "threat-103",
    cve: "CVE-2026-8910",
    vendor: "Linux Kernel Org",
    product: "Linux Kernel v6.12",
    threatType: "Remote Kernel Crash (DoS)",
    severity: "Critical",
    publishedDate: "2026-07-14",
    source: "Kernel Security Mailing List",
    summary: "A vulnerability in the netfilter subsystem of the Linux kernel enables remote actors to send crafted network packets that trigger a kernel panic.",
    remediation: "Recompile kernel with netfilter patch or upgrade default kernels to v6.12.3.",
    references: [
      "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
    ],
    cvssScore: 9.9,
    attackVector: "Network (AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H)",
    status: "investigating",
    countryCode: "RU",
    timestamp: "2026-07-17T06:05:00Z"
  },
  {
    id: "threat-104",
    cve: "CVE-2026-4011",
    vendor: "Cisco Systems",
    product: "Cisco IOS XE",
    threatType: "Authentication Bypass",
    severity: "Critical",
    publishedDate: "2026-07-08",
    source: "Cisco Advisory Desk",
    summary: "An architectural vulnerability in the web UI interface of Cisco IOS XE software allows a remote, unauthenticated attacker to bypass administrative authentication.",
    remediation: "Disable the HTTP Server utility on all Cisco routers reachable from the internet.",
    references: [
      "https://sec.cloud.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-iosxe-auth-bypass-4011"
    ],
    cvssScore: 9.1,
    attackVector: "Network (AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H)",
    status: "active",
    countryCode: "IR",
    timestamp: "2026-07-16T18:22:00Z"
  },
  {
    id: "threat-105",
    cve: "CVE-2026-3022",
    vendor: "Adobe Systems",
    product: "Acrobat Reader",
    threatType: "Memory Corruption (Out of Bounds)",
    severity: "High",
    publishedDate: "2026-06-25",
    source: "Adobe Security Center",
    summary: "An out-of-bounds write vulnerability occurs when parsing malformed 3D PDF assets in Adobe Acrobat Reader.",
    remediation: "Upgrade Adobe Acrobat Reader to the patch version v24.012.3 or newer.",
    references: [
      "https://helpx.adobe.com/security/products/acrobat/apsb26-3022.html"
    ],
    cvssScore: 8.1,
    attackVector: "Local/User (AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H)",
    status: "mitigated",
    countryCode: "NL",
    timestamp: "2026-07-15T11:30:00Z"
  },
  {
    id: "threat-106",
    cve: "CVE-2026-2810",
    vendor: "Apache Software Foundation",
    product: "Apache HTTP Server",
    threatType: "Path Traversal",
    severity: "Warning",
    publishedDate: "2026-05-12",
    source: "Apache Security Team",
    summary: "A misconfiguration allowance in rewrite rule configurations triggers path traversal capabilities on Apache HTTP Server instances.",
    remediation: "Update Apache HTTP Server to version 2.4.63.",
    references: [
      "https://httpd.apache.org/security/vulnerabilities_24.html"
    ],
    cvssScore: 7.5,
    attackVector: "Network (AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N)",
    status: "mitigated",
    countryCode: "DE",
    timestamp: "2026-07-14T14:45:00Z"
  },
  {
    id: "threat-107",
    cve: "CVE-2026-5109",
    vendor: "WordPress",
    product: "Gravity Forms Plugin",
    threatType: "Stored Cross-Site Scripting (XSS)",
    severity: "High",
    publishedDate: "2026-07-20",
    source: "NVD Directory API",
    summary: "The Gravity Forms plugin for WordPress is vulnerable to Stored Cross-Site Scripting via administrative form inputs in versions up to 2.8.12.",
    remediation: "Upgrade Gravity Forms plugin to version 2.8.13 or higher.",
    references: ["https://nvd.nist.gov/vuln/detail/CVE-2026-5109"],
    cvssScore: 7.2,
    attackVector: "Network",
    status: "active",
    countryCode: "US",
    timestamp: "2026-07-20T10:00:00Z"
  },
  {
    id: "threat-108",
    cve: "CVE-2026-2177",
    vendor: "Fortinet",
    product: "FortiOS & FortiProxy",
    threatType: "SSL-VPN Remote Code Execution",
    severity: "Critical",
    publishedDate: "2026-07-22",
    source: "Fortinet PSIRT",
    summary: "An out-of-bounds write vulnerability in FortiOS SSL-VPN web portal allows an unauthenticated remote attacker to execute arbitrary code via specially crafted requests.",
    remediation: "Upgrade FortiOS to version 7.4.4 or 7.2.8 immediately.",
    references: ["https://www.fortiguard.com/psirt/FG-IR-24-015"],
    cvssScore: 9.6,
    attackVector: "Network",
    status: "active",
    countryCode: "US",
    timestamp: "2026-07-22T08:30:00Z"
  },
  {
    id: "threat-109",
    cve: "CVE-2026-1730",
    vendor: "Ivanti",
    product: "Connect Secure VPN",
    threatType: "Command Injection Zero-Day",
    severity: "Critical",
    publishedDate: "2026-07-24",
    source: "CISA KEV Catalog",
    summary: "A command injection vulnerability in the web component of Ivanti Connect Secure allows remote unauthenticated attackers to execute arbitrary commands on target gateways.",
    remediation: "Apply Ivanti emergency patch script and perform IOC threat hunting.",
    references: ["https://forums.ivanti.com/s/article/KB-CVE-2026-1730"],
    cvssScore: 9.8,
    attackVector: "Network",
    status: "active",
    countryCode: "US",
    timestamp: "2026-07-24T14:10:00Z"
  },
  {
    id: "threat-110",
    cve: "CVE-2026-3305",
    vendor: "VMware",
    product: "ESXi Hypervisor",
    threatType: "Heap Overflow Escaping Sandbox",
    severity: "Critical",
    publishedDate: "2026-07-18",
    source: "VMware Security Advisory",
    summary: "A heap overflow flaw in ESXi VMX device emulation permits a virtual machine guest user to escape the VM sandbox and execute code on the host operating system.",
    remediation: "Apply ESXi ESXi80U2b-23305542 patch bundle.",
    references: ["https://www.vmware.com/security/advisories/VMSA-2026-0008.html"],
    cvssScore: 9.3,
    attackVector: "Local",
    status: "active",
    countryCode: "CA",
    timestamp: "2026-07-18T16:00:00Z"
  },
  {
    id: "threat-111",
    cve: "CVE-2026-6401",
    vendor: "Palo Alto Networks",
    product: "PAN-OS Management Web Interface",
    threatType: "Unauthenticated Command Injection",
    severity: "Critical",
    publishedDate: "2026-07-26",
    source: "PAN-OS Threat Intelligence",
    summary: "A command injection vulnerability in the management web interface of PAN-OS software allows an unauthenticated remote attacker to execute arbitrary root commands.",
    remediation: "Restrict management access to internal IPs or upgrade to PAN-OS 11.1.2-h3.",
    references: ["https://security.paloaltonetworks.com/CVE-2026-6401"],
    cvssScore: 10.0,
    attackVector: "Network",
    status: "active",
    countryCode: "US",
    timestamp: "2026-07-26T12:00:00Z"
  },
  {
    id: "threat-112",
    cve: "CVE-2026-4890",
    vendor: "GitLab",
    product: "GitLab Community & Enterprise Edition",
    threatType: "Arbitrary File Read via Pipeline",
    severity: "High",
    publishedDate: "2026-07-15",
    source: "GitLab Security Release",
    summary: "An issue in GitLab CE/EE affects all versions starting from 16.0 before 16.11.3 where pipeline artifact processing allowed unauthorized file reads.",
    remediation: "Upgrade GitLab instance to 16.11.3, 17.0.2, or 17.1.1 immediately.",
    references: ["https://about.gitlab.com/releases/2026/07/15/security-release/"],
    cvssScore: 8.7,
    attackVector: "Network",
    status: "mitigated",
    countryCode: "FR",
    timestamp: "2026-07-15T09:30:00Z"
  },
  {
    id: "threat-113",
    cve: "CVE-2026-8802",
    vendor: "Atlassian",
    product: "Confluence Data Center",
    threatType: "OGNL Remote Code Execution",
    severity: "Critical",
    publishedDate: "2026-07-21",
    source: "Atlassian Advisory",
    summary: "An OGNL injection vulnerability in Confluence Server and Data Center allows unauthenticated attackers to execute arbitrary code on vulnerable Confluence instances.",
    remediation: "Upgrade Confluence Data Center to version 8.5.9 or 8.9.1.",
    references: ["https://confluence.atlassian.com/doc/confluence-security-advisory-2026-07-21"],
    cvssScore: 9.1,
    attackVector: "Network",
    status: "active",
    countryCode: "AU",
    timestamp: "2026-07-21T11:45:00Z"
  },
  {
    id: "threat-114",
    cve: "CVE-2026-10222",
    vendor: "VulnDB CNA",
    product: "Gist Repository Engine",
    threatType: "Injection Payload",
    severity: "Warning",
    publishedDate: "2026-06-01",
    source: "NVD API Directory",
    summary: "Vulnerability CVE-2026-10222 involves string parsing weaknesses in markdown renderer assets.",
    remediation: "Sanitize user inputs across form endpoints.",
    references: ["https://nvd.nist.gov/vuln/detail/CVE-2026-10222"],
    cvssScore: 5.6,
    attackVector: "Network",
    status: "active",
    countryCode: "US",
    timestamp: "2026-06-01T13:16:00Z"
  }
];
